version: '3.8'  # Docker Compose versiyonu

services:
  web:
    image: your-web-app-image:latest
    build: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
